<a href="https://colab.research.google.com/github/alexandreleitetrevisani/DATA_SCIENCE_MACHINE_LEARNING/blob/master/Census_DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [0]:
file = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
colunas = ['age','workclass','final-weight','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
train = pd.read_csv(file,names=colunas,usecols=colunas)
train.head()

age          workclass  final-weight  ... hours-per-week  native-country  income
0   39          State-gov         77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...             13   United-States   <=50K
2   38            Private        215646  ...             40   United-States   <=50K
3   53            Private        234721  ...             40   United-States   <=50K
4   28            Private        338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [0]:
train.columns

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [0]:
# já não tem a coluna income
previsores = train.iloc[:,0:14].values
previsores

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [0]:
classe = train.iloc[:,14].values
classe

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
labelencoder_previsores = LabelEncoder()

In [0]:
previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])


In [0]:
previsores[:,3]

array([9, 9, 11, ..., 11, 11, 11], dtype=object)

In [0]:
previsores[:,9]

array([1, 1, 1, ..., 0, 1, 0], dtype=object)

In [0]:
train['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other'], dtype=object)

In [0]:
onehotencoder = OneHotEncoder()
previsores = onehotencoder.fit_transform(previsores).toarray()


In [0]:
previsores

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [0]:
previsores.shape

(32561, 22144)

In [0]:
labelencoder_classe = LabelEncoder()
classe = labelencoder_classe.fit_transform(classe)

In [0]:
classe

array([0, 0, 0, ..., 0, 0, 1])

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
scaler = StandardScaler()

In [0]:
previsores = scaler.fit_transform(previsores)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
previsores_train, previsores_test, classe_train, classe_test = train_test_split(previsores,classe, test_size=0.20, random_state=0)

In [0]:
from sklearn.tree import DecisionTreeClassifier

In [0]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(previsores_train,classe_train)
previsoes = classifier.predict(previsores_test)

In [0]:
previsoes

array([0, 0, 0, ..., 1, 0, 1])

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
precisao = accuracy_score(classe_test,previsoes)
matriz = confusion_matrix(classe_test,previsoes)

In [0]:
precisao

0.8063872255489022

In [0]:
matriz

array([[4251,  667],
       [ 594, 1001]])